---
kind: Service
apiVersion: v1
metadata:
  name: thumb-endp
  namespace: imageapp
spec:
  selector:
    app: thumb-endp
  ports:
  - name: http
    protocol: TCP
    port: 5555
    targetPort: 5555
