---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: thumb-endp
  namespace: imageapp
  labels:
    app: thumb-endp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thumb-endp
  template:
    metadata:
      labels:
        app: thumb-endp
    spec:
      containers:
        - name: thumb-endp
          image: registry.pineapple.no-ip.biz:30004/imageapp/thumb_endp:latest
        


