---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapidemo
  name: webapidemo
  namespace: webapidemo
spec:
  type: NodePort
  ports:
  - port: 5555
    nodePort: 30006
  selector:
    app: webapidemo

---
kind: Service
apiVersion: v1
metadata:
  name: webapidemo-internal
  namespace: webapidemo
spec:
  selector:
    app: webapidemo
  ports:
  - name: http
    protocol: TCP
    port: 5555
    targetPort: 5555
